In [16]:
import pandas as pd
from sqlalchemy import create_engine

In [17]:
csv_file = "consolidated_coin_data.csv"
coin_data_df= pd.read_csv(csv_file)
coin_data_df.head()

,Currency,Date,Open,High,Low,Close,Volume,Market Cap
0,ripple,"Apr 24, 2019",0.321114,0.321282,0.296982,0.302318,"1,517,791,002","12,698,877,293"
1,ripple,"Apr 23, 2019",0.323844,0.328396,0.320919,0.321222,"1,077,333,990","13,492,933,875"
2,ripple,"Apr 22, 2019",0.322277,0.329350,0.320237,0.323934,"1,131,094,080","13,606,823,301"
3,ripple,"Apr 21, 2019",0.328678,0.329627,0.318746,0.322449,"1,005,803,846","13,533,407,430"
4,ripple,"Apr 20, 2019",0.331871,0.333213,0.324969,0.328476,"931,570,799","13,786,384,592"

In [18]:
coin_data_df.set_index('Date', inplace=True)
coin_data_df.head()

,Currency,Open,High,Low,Close,Volume,Market Cap
Date,,,,,,,
"Apr 24, 2019",ripple,0.321114,0.321282,0.296982,0.302318,"1,517,791,002","12,698,877,293"
"Apr 23, 2019",ripple,0.323844,0.328396,0.320919,0.321222,"1,077,333,990","13,492,933,875"
"Apr 22, 2019",ripple,0.322277,0.329350,0.320237,0.323934,"1,131,094,080","13,606,823,301"
"Apr 21, 2019",ripple,0.328678,0.329627,0.318746,0.322449,"1,005,803,846","13,533,407,430"
"Apr 20, 2019",ripple,0.331871,0.333213,0.324969,0.328476,"931,570,799","13,786,384,592"

In [19]:
coin_data_df['Low'].min()

0.001227

In [20]:
coin_data_df['High'].max()

20089.0

In [25]:
engine = create_engine("postgresql+psycopg2://postgres:password@localhost/crypto")
coin_data_df.to_sql("crypto2",engine,if_exists='replace',index='date')

In [27]:
coin_data_df2=pd.read_sql("""Select * from crypto2
                          """,engine )

In [28]:
coin_data_df2

,date,Currency,Open,High,Low,Close,Volume,Market Cap
0,"Apr 24, 2019",ripple,0.321114,0.321282,0.296982,0.302318,"1,517,791,002","12,698,877,293"
1,"Apr 23, 2019",ripple,0.323844,0.328396,0.320919,0.321222,"1,077,333,990","13,492,933,875"
2,"Apr 22, 2019",ripple,0.322277,0.329350,0.320237,0.323934,"1,131,094,080","13,606,823,301"
3,"Apr 21, 2019",ripple,0.328678,0.329627,0.318746,0.322449,"1,005,803,846","13,533,407,430"
4,"Apr 20, 2019",ripple,0.331871,0.333213,0.324969,0.328476,"931,570,799","13,786,384,592"
5,"Apr 19, 2019",ripple,0.337062,0.337147,0.329577,0.331902,"1,025,167,554","13,930,181,415"
6,"Apr 18, 2019",ripple,0.335476,0.345289,0.335335,0.337065,"1,092,731,769","14,146,855,828"
7,"Apr 17, 2019",ripple,0.327157,0.340327,0.322388,0.335453,"1,137,811,633","14,079,207,980"
8,"Apr 16, 2019",ripple,0.320998,0.327308,0.319261,0.327218,"799,796,781","13,733,570,917"
9,"Apr 15, 2019",ripple,0.328841,0.331551,0.318090,0.320913,"934,107,164","13,468,978,197"
10,"Apr 14, 2019",ripple,0.326160,0.329421,0.324244,0.328809,"746,765,729","13,741,639,599"
11,"Apr 13, 2019",ripple,0.326386,0.334444,0.323714,0.326031,"976,688,780","13,625,508,289"
12,"Apr 12, 2019",ripple,0.330664,0.330868,0.321167,0.326346,"1,076,074,031","13,638,700,669"
13,"Apr 11, 2019",ripple,0.354828,0.354851,0.326826,0.330984,"1,641,951,210","13,832,528,015"
14,"Apr 10, 2019",ripple,0.349425,0.359778,0.348709,0.354792,"1,213,341,089","14,827,516,669"
15,"Apr 09, 2019",ripple,0.358307,0.358307,0.348536,0.349462,"1,076,688,924","14,604,743,889"
16,"Apr 08, 2019",ripple,0.361143,0.367036,0.351588,0.358234,"1,513,421,926","14,971,342,083"
17,"Apr 07, 2019",ripple,0.354406,0.365387,0.351689,0.359856,"1,398,086,395","15,021,731,305"
18,"Apr 06, 2019",ripple,0.361837,0.363441,0.351168,0.354405,"1,440,643,534","14,794,185,026"
19,"Apr 05, 2019",ripple,0.332685,0.374064,0.332630,0.361803,"2,359,353,481","15,103,004,666"
20,"Apr 04, 2019",ripple,0.342286,0.348977,0.329070,0.332513,"1,599,115,419","13,880,340,560"
21,"Apr 03, 2019",ripple,0.351309,0.371270,0.333735,0.342234,"2,544,122,431","14,286,134,859"
22,"Apr 02, 2019",ripple,0.312805,0.355870,0.312001,0.351499,"2,400,198,268","14,672,900,148"
23,"Apr 01, 2019",ripple,0.309195,0.313777,0.308910,0.312747,"836,123,225","13,043,585,711"
24,"Mar 31, 2019",ripple,0.310730,0.311171,0.308150,0.309229,"652,757,652","12,896,872,922"
25,"Mar 30, 2019",ripple,0.307655,0.326784,0.306873,0.310632,"929,122,633","12,955,391,175"
26,"Mar 29, 2019",ripple,0.309269,0.311644,0.306235,0.307929,"854,583,316","12,842,645,325"
27,"Mar 28, 2019",ripple,0.312383,0.312452,0.307085,0.309246,"677,929,379","12,897,607,540"
28,"Mar 27, 2019",ripple,0.305421,0.312615,0.304067,0.312465,"781,951,318","13,031,827,698"
29,"Mar 26, 2019",ripple,0.303808,0.305060,0.298987,0.305060,"761,000,017","12,722,986,423"
...,...,...,...,...,...,...,...,...
13546,"Oct 30, 2017",cardano,0.028318,0.028874,0.027586,0.028583,"3,781,270","741,070,864"
13547,"Oct 29, 2017",cardano,0.025831,0.029837,0.025626,0.028607,"4,746,180","741,693,114"
13548,"Oct 28, 2017",cardano,0.026339,0.026853,0.025593,0.025866,"1,739,460","670,632,199"
13549,"Oct 27, 2017",cardano,0.027138,0.027463,0.025674,0.026382,"2,511,440","684,002,790"
13550,"Oct 26, 2017",cardano,0.027409,0.027560,0.026478,0.027132,"2,437,710","703,448,092"
13551,"Oct 25, 2017",cardano,0.027038,0.027846,0.026107,0.027527,"2,561,430","713,707,434"
13552,"Oct 24, 2017",cardano,0.025339,0.028956,0.023766,0.027193,"7,589,560","705,027,051"
13553,"Oct 23, 2017",cardano,0.027684,0.028051,0.024345,0.025454,"3,517,050","659,937,283"
13554,"Oct 22, 2017",cardano,0.028565,0.028744,0.027093,0.027729,"2,930,210","718,926,554"
13555,"Oct 21, 2017",cardano,0.030806,0.030806,0.027977,0.028436,"5,344,520","737,267,363"
13556,"Oct 20, 2017",cardano,0.026982,0.030855,0.026612,0.030630,"8,716,410","794,140,985"
13557,"Oct 19, 2017",cardano,0.026704,0.027112,0.025772,0.027032,"2,897,720","700,857,978"
13558,"Oct 18, 2017",cardano,0.027219,0.027360,0.024637,0.026691,"2,336,180","692,011,662"
13559,"Oct 17, 2017",cardano,0.028953,0.029628,0.025481,0.027217,"7,039,900","705,670,042"
13560,"Oct 16, 2017",cardano,0.029939,0.030749,0.028577,0.028948,"6,196,030","750,542,023"
13561,"Oct 15, 2017",cardano,0.032874,0.033641,0.028694,0.030049,"7,104,990","779,072,172"
13562,"Oct 14, 2017",cardano,0.033876,0.038268,0.029255,0.032465,"27,853,200","841,719,752"
13563,"Oct 13, 2017",cardano,0.026061,0.033816,0.025195,0.033641,"15,613,600","872,212,580"
13564,"Oct 12, 2017",cardano,0.022538,0.026763,0.021825,0.026252,"8,680,640","680,640,048"
13565,"Oct 11, 2017",cardano,0.021480,0.022576,0.020976,0.022520,"3,606,720","583,864,665"
13566,"Oct 10, 2017",cardano,0.022112,0.022446,0.021279,0.021531,"2,725,600","558,243,534"
13567,"Oct 09, 2017",cardano,0.020344,0.022807,0.020342,0.022114,"4,663,310","573,343,460"
13568,"Oct 08, 2017",cardano,0.020929,0.023598,0.020147,0.020477,"7,727,460","530,913,809"
13569,"Oct 07, 2017",cardano,0.018414,0.021050,0.017620,0.020941,"7,411,240","542,936,191"
13570,"Oct 06, 2017",cardano,0.021359,0.021542,0.018360,0.018539,"7,780,710","480,664,553"
13571,"Oct 05, 2017",cardano,0.021951,0.022154,0.020859,0.021489,"5,562,510","557,139,041"
13572,"Oct 04, 2017",cardano,0.020864,0.022806,0.020864,0.021931,"9,000,050","568,619,548"
13573,"Oct 03, 2017",cardano,0.025757,0.027425,0.020690,0.020816,"16,997,800","539,692,715"
13574,"Oct 02, 2017",cardano,0.024607,0.030088,0.019969,0.025932,"57,641,300","628,899,052"
13575,"Oct 01, 2017",cardano,0.021678,0.032226,0.017354,0.024969,"50,068,700",-