In [20]:
import pandas as pd
from sqlalchemy import create_engine

In [21]:
url="https://coinmarketcap.com/currencies/ripple/historical-data/?start=20130428&end=20190821"

In [22]:
#webscraping
tables = pd.read_html(url)
tables

[              Date     Open*      High       Low   Close**      Volume  \
 0     Aug 21, 2019  0.275765  0.275765  0.260688  0.266261  1164536124
 1     Aug 20, 2019  0.283159  0.283241  0.273442  0.275806  1056822925
 2     Aug 19, 2019  0.282290  0.289091  0.278425  0.283328  1241578947
 3     Aug 18, 2019  0.265714  0.288718  0.263579  0.282646  1216547019
 4     Aug 17, 2019  0.261885  0.268046  0.259252  0.265721  1004931822
 5     Aug 16, 2019  0.265075  0.265452  0.256977  0.261971  1133224404
 6     Aug 15, 2019  0.263707  0.268241  0.256112  0.264882  1342788578
 7     Aug 14, 2019  0.296719  0.297220  0.252390  0.263343  1794754610
 8     Aug 13, 2019  0.300661  0.301178  0.293562  0.296639   853175560
 9     Aug 12, 2019  0.302169  0.303528  0.298506  0.300322   762308356
 10    Aug 11, 2019  0.298566  0.306181  0.296911  0.301915   838671654
 11    Aug 10, 2019  0.297245  0.304747  0.293443  0.298721  1077459339
 12    Aug 09, 2019  0.307567  0.308218  0.293271  0.297343  1021136188
 13    Aug 08, 2019  0.311785  0.312618  0.305112  0.307661   907305889
 14    Aug 07, 2019  0.311492  0.315573  0.308720  0.311969   967534123
 15    Aug 06, 2019  0.324018  0.324946  0.308895  0.311326  1069603911
 16    Aug 05, 2019  0.319723  0.331414  0.319410  0.323564  1203381139
 17    Aug 04, 2019  0.316862  0.322925  0.312325  0.319842   926896287
 18    Aug 03, 2019  0.312506  0.319651  0.311696  0.316757   789419360
 19    Aug 02, 2019  0.317809  0.318876  0.310844  0.312394   816728848
 20    Aug 01, 2019  0.320734  0.320851  0.313134  0.317906   882867288
 21    Jul 31, 2019  0.317887  0.322465  0.317244  0.320909   996700948
 22    Jul 30, 2019  0.311090  0.320407  0.307865  0.318470   928714010
 23    Jul 29, 2019  0.311996  0.313812  0.308020  0.310658   807093679
 24    Jul 28, 2019  0.310631  0.312774  0.304110  0.312288   846655034
 25    Jul 27, 2019  0.323512  0.326285  0.307301  0.310528  1163969614
 26    Jul 26, 2019  0.314740  0.324508  0.309720  0.323530  1039753781
 27    Jul 25, 2019  0.315859  0.321363  0.313881  0.314810  1086214216
 28    Jul 24, 2019  0.309885  0.316471  0.305276  0.315947  1222619064
 29    Jul 23, 2019  0.322267  0.322349  0.307652  0.309926  1015322888
 ...            ...       ...       ...       ...       ...         ...
 2179  Sep 02, 2013  0.005799  0.006115  0.005507  0.005528           -
 2180  Sep 01, 2013  0.005623  0.005872  0.005574  0.005787           -
 2181  Aug 31, 2013  0.005913  0.006081  0.005576  0.005632           -
 2182  Aug 30, 2013  0.005760  0.006264  0.005610  0.005930           -
 2183  Aug 29, 2013  0.006246  0.006246  0.005756  0.005763           -
 2184  Aug 28, 2013  0.006451  0.006463  0.006066  0.006246           -
 2185  Aug 27, 2013  0.006468  0.006936  0.006373  0.006452           -
 2186  Aug 26, 2013  0.006104  0.006507  0.006065  0.006417           -
 2187  Aug 25, 2013  0.005526  0.006148  0.005519  0.006104           -
 2188  Aug 24, 2013  0.005139  0.005603  0.005126  0.005546           -
 2189  Aug 23, 2013  0.005179  0.005232  0.004919  0.005139           -
 2190  Aug 22, 2013  0.006131  0.006138  0.005143  0.005143           -
 2191  Aug 21, 2013  0.006098  0.006349  0.005950  0.006131           -
 2192  Aug 20, 2013  0.005376  0.006158  0.005309  0.006098           -
 2193  Aug 19, 2013  0.005587  0.005839  0.005223  0.005260           -
 2194  Aug 18, 2013  0.005687  0.006263  0.005585  0.005617           -
 2195  Aug 17, 2013  0.003138  0.005683  0.003138  0.005671           -
 2196  Aug 16, 2013  0.003082  0.003162  0.002875  0.003134           -
 2197  Aug 15, 2013  0.003788  0.003804  0.003067  0.003092           -
 2198  Aug 14, 2013  0.004267  0.004267  0.003785  0.003788           -
 2199  Aug 13, 2013  0.004463  0.004463  0.004171  0.004245           -
 2200  Aug 12, 2013  0.004414  0.004520  0.004359  0.004449           -
 2201  Aug 11, 2013  0.004314  0.004421  0.004300  0.004415           -
 2202  Aug 10, 2013  0.004291  0.004366  0.004279  0.004314           -
 2203  Aug 09, 2013  0.004257  0.004367  0.004253  0.004291           -
 2204  Aug 08, 2013  0.004397  0.004424  0.004175  0.004254           -
 2205  Aug 07, 2013  0.004669  0.004682  0.004333  0.004417           -
 2206  Aug 06, 2013  0.005637  0.005661  0.004629  0.004680           -
 2207  Aug 05, 2013  0.005875  0.005980  0.005613  0.005613           -
 2208  Aug 04, 2013  0.005874  0.005927  0.005874  0.005882           -

        Market Cap
 0     11420125836
 1     11829516782
 2     12152144825
 3     12122901988
 4     11396948393
 5     11236137963
 6     11360984400
 7     11294964982
 8     12723035972
 9     12881006909
 10    12943909474
 11    12806941381
 12    12747895720
 13    13190251227
 14    13374954845
 15    13347360882
 16    13872050658
 17    13712472285
 18    13580218029
 19    13393149204
 20    13629460730
 21    13758215467
 22    13653644725
 23    13318731525
 24    13376153627
 25    13300742951
 26    13857657307
 27    13484184546
 28    13532870285
 29    13274967598
 ...           ...
 2179     43216200
 2180     45239783
 2181     44028635
 2182     46362745
 2183     45051372
 2184     48830305
 2185     50441338
 2186     50166773
 2187     47719539
 2188     43357939
 2189     40172930
 2190     40205218
 2191     47928746
 2192     47673883
 2193     41125306
 2194     43916527
 2195     44335331
 2196     24497514
 2197     24172681
 2198     29617450
 2199     33190304
 2200     34778195
 2201     34518485
 2202     33724969
 2203     33547503
 2204     33258632
 2205     34534121
 2206     36591008
 2207     43879157
 2208     45983577

 [2209 rows x 7 columns],
                            0                            1
 0                  XRP Price                 0.274927 USD
 1                    XRP ROI                    +4580.54%
 2                Market Rank                           #3
 3                 Market Cap           11,796,996,836 USD
 4             24 Hour Volume              964,209,596 USD
 5         Circulating Supply           42,909,539,227 XRP
 6               Total Supply           99,991,371,628 XRP
 7                 Max Supply          100,000,000,000 XRP
 8              All Time High      3.84 USD (Jan 04, 2018)
 9               All Time Low  0.002802 USD (Jul 07, 2014)
 10        52 Week High / Low  0.769380 USD / 0.252390 USD
 11         90 Day High / Low  0.505467 USD / 0.252390 USD
 12         30 Day High / Low  0.331414 USD / 0.252390 USD
 13          7 Day High / Low  0.289091 USD / 0.259252 USD
 14        24 Hour High / Low  0.277568 USD / 0.268889 USD
 15    Yesterday's High / Low  0.277568 USD / 0.268560 USD
 16  Yesterday's Open / Close  0.270575 USD / 0.276545 USD
 17        Yesterday's Change       $0.005970 USD (+2.21%)
 18        Yesterday's Volume             $999,419,343 USD]

In [23]:
#createdataframe
df = tables[0]
df.columns = ["Date","Open","High","Low","Close","Volume","Market Cap"]
df.head()

,Date,Open,High,Low,Close,Volume,Market Cap
0,"Aug 21, 2019",0.275765,0.275765,0.260688,0.266261,1164536124,11420125836
1,"Aug 20, 2019",0.283159,0.283241,0.273442,0.275806,1056822925,11829516782
2,"Aug 19, 2019",0.282290,0.289091,0.278425,0.283328,1241578947,12152144825
3,"Aug 18, 2019",0.265714,0.288718,0.263579,0.282646,1216547019,12122901988
4,"Aug 17, 2019",0.261885,0.268046,0.259252,0.265721,1004931822,11396948393

In [24]:
#cleanupdata
df = df.iloc[2:]
df.head()

,Date,Open,High,Low,Close,Volume,Market Cap
2,"Aug 19, 2019",0.282290,0.289091,0.278425,0.283328,1241578947,12152144825
3,"Aug 18, 2019",0.265714,0.288718,0.263579,0.282646,1216547019,12122901988
4,"Aug 17, 2019",0.261885,0.268046,0.259252,0.265721,1004931822,11396948393
5,"Aug 16, 2019",0.265075,0.265452,0.256977,0.261971,1133224404,11236137963
6,"Aug 15, 2019",0.263707,0.268241,0.256112,0.264882,1342788578,11360984400

In [25]:
df.set_index('Date', inplace=True)
df.head()

                  Open      High       Low     Close      Volume   Market Cap
Date
Aug 19, 2019  0.282290  0.289091  0.278425  0.283328  1241578947  12152144825
Aug 18, 2019  0.265714  0.288718  0.263579  0.282646  1216547019  12122901988
Aug 17, 2019  0.261885  0.268046  0.259252  0.265721  1004931822  11396948393
Aug 16, 2019  0.265075  0.265452  0.256977  0.261971  1133224404  11236137963
Aug 15, 2019  0.263707  0.268241  0.256112  0.264882  1342788578  11360984400

In [26]:
df['Low'].min()

0.002802

In [27]:
df['High'].max()

3.84

In [37]:
engine = create_engine("postgresql+psycopg2://postgres:password@localhost/crypto")

In [38]:
df.to_sql("crypto",engine,if_exists='replace',index='date')

In [39]:
df2=pd.read_sql("""Select * from crypto
                          """,engine)

In [40]:
df2

,date,Currency,Open,High,Low,Close,Volume,Market Cap
0,"Apr 24, 2019",ripple,0.321114,0.321282,0.296982,0.302318,"1,517,791,002","12,698,877,293"
1,"Apr 23, 2019",ripple,0.323844,0.328396,0.320919,0.321222,"1,077,333,990","13,492,933,875"
2,"Apr 22, 2019",ripple,0.322277,0.329350,0.320237,0.323934,"1,131,094,080","13,606,823,301"
3,"Apr 21, 2019",ripple,0.328678,0.329627,0.318746,0.322449,"1,005,803,846","13,533,407,430"
4,"Apr 20, 2019",ripple,0.331871,0.333213,0.324969,0.328476,"931,570,799","13,786,384,592"
5,"Apr 19, 2019",ripple,0.337062,0.337147,0.329577,0.331902,"1,025,167,554","13,930,181,415"
6,"Apr 18, 2019",ripple,0.335476,0.345289,0.335335,0.337065,"1,092,731,769","14,146,855,828"
7,"Apr 17, 2019",ripple,0.327157,0.340327,0.322388,0.335453,"1,137,811,633","14,079,207,980"
8,"Apr 16, 2019",ripple,0.320998,0.327308,0.319261,0.327218,"799,796,781","13,733,570,917"
9,"Apr 15, 2019",ripple,0.328841,0.331551,0.318090,0.320913,"934,107,164","13,468,978,197"
10,"Apr 14, 2019",ripple,0.326160,0.329421,0.324244,0.328809,"746,765,729","13,741,639,599"
11,"Apr 13, 2019",ripple,0.326386,0.334444,0.323714,0.326031,"976,688,780","13,625,508,289"
12,"Apr 12, 2019",ripple,0.330664,0.330868,0.321167,0.326346,"1,076,074,031","13,638,700,669"
13,"Apr 11, 2019",ripple,0.354828,0.354851,0.326826,0.330984,"1,641,951,210","13,832,528,015"
14,"Apr 10, 2019",ripple,0.349425,0.359778,0.348709,0.354792,"1,213,341,089","14,827,516,669"
15,"Apr 09, 2019",ripple,0.358307,0.358307,0.348536,0.349462,"1,076,688,924","14,604,743,889"
16,"Apr 08, 2019",ripple,0.361143,0.367036,0.351588,0.358234,"1,513,421,926","14,971,342,083"
17,"Apr 07, 2019",ripple,0.354406,0.365387,0.351689,0.359856,"1,398,086,395","15,021,731,305"
18,"Apr 06, 2019",ripple,0.361837,0.363441,0.351168,0.354405,"1,440,643,534","14,794,185,026"
19,"Apr 05, 2019",ripple,0.332685,0.374064,0.332630,0.361803,"2,359,353,481","15,103,004,666"
20,"Apr 04, 2019",ripple,0.342286,0.348977,0.329070,0.332513,"1,599,115,419","13,880,340,560"
21,"Apr 03, 2019",ripple,0.351309,0.371270,0.333735,0.342234,"2,544,122,431","14,286,134,859"
22,"Apr 02, 2019",ripple,0.312805,0.355870,0.312001,0.351499,"2,400,198,268","14,672,900,148"
23,"Apr 01, 2019",ripple,0.309195,0.313777,0.308910,0.312747,"836,123,225","13,043,585,711"
24,"Mar 31, 2019",ripple,0.310730,0.311171,0.308150,0.309229,"652,757,652","12,896,872,922"
25,"Mar 30, 2019",ripple,0.307655,0.326784,0.306873,0.310632,"929,122,633","12,955,391,175"
26,"Mar 29, 2019",ripple,0.309269,0.311644,0.306235,0.307929,"854,583,316","12,842,645,325"
27,"Mar 28, 2019",ripple,0.312383,0.312452,0.307085,0.309246,"677,929,379","12,897,607,540"
28,"Mar 27, 2019",ripple,0.305421,0.312615,0.304067,0.312465,"781,951,318","13,031,827,698"
29,"Mar 26, 2019",ripple,0.303808,0.305060,0.298987,0.305060,"761,000,017","12,722,986,423"
...,...,...,...,...,...,...,...,...
13546,"Oct 30, 2017",cardano,0.028318,0.028874,0.027586,0.028583,"3,781,270","741,070,864"
13547,"Oct 29, 2017",cardano,0.025831,0.029837,0.025626,0.028607,"4,746,180","741,693,114"
13548,"Oct 28, 2017",cardano,0.026339,0.026853,0.025593,0.025866,"1,739,460","670,632,199"
13549,"Oct 27, 2017",cardano,0.027138,0.027463,0.025674,0.026382,"2,511,440","684,002,790"
13550,"Oct 26, 2017",cardano,0.027409,0.027560,0.026478,0.027132,"2,437,710","703,448,092"
13551,"Oct 25, 2017",cardano,0.027038,0.027846,0.026107,0.027527,"2,561,430","713,707,434"
13552,"Oct 24, 2017",cardano,0.025339,0.028956,0.023766,0.027193,"7,589,560","705,027,051"
13553,"Oct 23, 2017",cardano,0.027684,0.028051,0.024345,0.025454,"3,517,050","659,937,283"
13554,"Oct 22, 2017",cardano,0.028565,0.028744,0.027093,0.027729,"2,930,210","718,926,554"
13555,"Oct 21, 2017",cardano,0.030806,0.030806,0.027977,0.028436,"5,344,520","737,267,363"
13556,"Oct 20, 2017",cardano,0.026982,0.030855,0.026612,0.030630,"8,716,410","794,140,985"
13557,"Oct 19, 2017",cardano,0.026704,0.027112,0.025772,0.027032,"2,897,720","700,857,978"
13558,"Oct 18, 2017",cardano,0.027219,0.027360,0.024637,0.026691,"2,336,180","692,011,662"
13559,"Oct 17, 2017",cardano,0.028953,0.029628,0.025481,0.027217,"7,039,900","705,670,042"
13560,"Oct 16, 2017",cardano,0.029939,0.030749,0.028577,0.028948,"6,196,030","750,542,023"
13561,"Oct 15, 2017",cardano,0.032874,0.033641,0.028694,0.030049,"7,104,990","779,072,172"
13562,"Oct 14, 2017",cardano,0.033876,0.038268,0.029255,0.032465,"27,853,200","841,719,752"
13563,"Oct 13, 2017",cardano,0.026061,0.033816,0.025195,0.033641,"15,613,600","872,212,580"
13564,"Oct 12, 2017",cardano,0.022538,0.026763,0.021825,0.026252,"8,680,640","680,640,048"
13565,"Oct 11, 2017",cardano,0.021480,0.022576,0.020976,0.022520,"3,606,720","583,864,665"
13566,"Oct 10, 2017",cardano,0.022112,0.022446,0.021279,0.021531,"2,725,600","558,243,534"
13567,"Oct 09, 2017",cardano,0.020344,0.022807,0.020342,0.022114,"4,663,310","573,343,460"
13568,"Oct 08, 2017",cardano,0.020929,0.023598,0.020147,0.020477,"7,727,460","530,913,809"
13569,"Oct 07, 2017",cardano,0.018414,0.021050,0.017620,0.020941,"7,411,240","542,936,191"
13570,"Oct 06, 2017",cardano,0.021359,0.021542,0.018360,0.018539,"7,780,710","480,664,553"
13571,"Oct 05, 2017",cardano,0.021951,0.022154,0.020859,0.021489,"5,562,510","557,139,041"
13572,"Oct 04, 2017",cardano,0.020864,0.022806,0.020864,0.021931,"9,000,050","568,619,548"
13573,"Oct 03, 2017",cardano,0.025757,0.027425,0.020690,0.020816,"16,997,800","539,692,715"
13574,"Oct 02, 2017",cardano,0.024607,0.030088,0.019969,0.025932,"57,641,300","628,899,052"
13575,"Oct 01, 2017",cardano,0.021678,0.032226,0.017354,0.024969,"50,068,700",-